//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenWebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CanteenDBContext : DbContext
    {
        public CanteenDBContext()
            : base("name=CanteenDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<food> food { get; set; }
        public virtual DbSet<image> image { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<order_list> order_list { get; set; }
        public virtual DbSet<user_list> Users { get; set; }
        public virtual DbSet<administrator> administrator { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<food_availability> food_availability { get; set; }
    }
}
