//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public short category_id { get; set; }
        public string category_name { get; set; }
        public short food_id { get; set; }
        public string description { get; set; }
    
        public virtual food food { get; set; }
    }
}
