//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public short order_id { get; set; }
        public short food_id { get; set; }
        public int quantity { get; set; }
        public int price { get; set; }
    
        public virtual food food { get; set; }
        public virtual order_list order_list { get; set; }
    }
}
